version: "3.7"
services:

    # This redis is setup without auth
    # this is just for local testing
    deblurring-redis:
        image: redis:latest
        ports:
            - 7001:6379
        container_name: deblurring-redis

    deblurring-database:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: deblurrer
        ports:
            - 6543:5432
        container_name: deblurring-database

    deblurring-serving:
        environment:
            - MODEL_NAME=deblurrer
            - PORT=8501
        build: ./serving
        image: deblurring-serving:latest
        ports:
            - 8501:8501
        container_name: deblurring-serving

    deblurring-backend:
        build: ./backend
        image: deblurring-backend:latest
        ports:
            - 8000:8000
        volumes:
            - ./backend:/deep-deblurring-backend
        depends_on:
            - deblurring-database
            - deblurring-redis
            - deblurring-serving
        container_name: deblurring-backend

    deblurring-frontend:
        build: ./frontend
        image: deblurring-frontend:latest
        ports:
            - 8081:8080
        volumes:
            - ./frontend:/deep-deblurring-frontend
        depends_on:
            - deblurring-backend
            - deblurring-serving
        container_name: deblurring-frontend
